[www]

; Utilisateur et groupe (standard Debian)
user = www-data
group = www-data

; on ecoute sur le port 9000 pour que nginx soit relie
listen = 9000

; Gestion dynamique des processus (valeurs par défaut du fichier original)
pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3

; pour que PHP puisse voir les variables MYSQL_ exportées par Docker
clear_env = no
